fix: reorganize this for devcontainer cli
The devcontainer cli likes to fight you with it's command line options
if the image directories don't have their container definitions inside
of a .devcontainer directory.

diff --git a/src/devcontainer-base/.devcontainer/Dockerfile b/src/devcontainer-base/.devcontainer/Dockerfile
--- a/src/devcontainer-base/.devcontainer/Dockerfile
+++ b/src/devcontainer-base/.devcontainer/Dockerfile
@@ -5,8 +5,6 @@ ARG VARIANT="noble"
 
 ARG LANG="en_US.UTF-8"
 
-ARG HOSTNAME="ubuntu-container"
-
 ARG USERNAME="vscode"
 ARG USER_UID="1000"
 ARG USER_GID="1000"
@@ -21,7 +19,7 @@ SHELL [ "/bin/bash", "-c" ]
 ARG VARIANT
 RUN if [ "$VARIANT" = "noble" ]; then \
         if id "ubuntu" &>/dev/null; then \
-            echo "Deleting user 'ubuntu'  for $VARIANT" && userdel -f -r ubuntu || echo "Failed to delete ubuntu user for $VARIANT"; \
+            echo "Deleting user 'ubuntu'  for $VARIANT" && userdel -f -r ubuntu || echo "Failed to delete ubuntu user for VARIANT";\
         else \
             echo "User 'ubuntu' does not exist for $VARIANT"; \
         fi; \
@@ -34,24 +32,21 @@ RUN --mount=type=cache,target=/var/cache/apt,sharing=locked,id=apt-cache \
   <<EOF
 export DEBIAN_FRONTEND=noninteractive
 apt-get update
-apt-get install -y --no-install-recommends \
-  sudo man-db manpages locales \
-  unzip zip gzip curl apt-utils openssh-client gnupg2 ca-certificates
-locale-gen "$LANG"
+apt-get install -y --no-install-recommends lsb-release init-system-helpers \
+  sudo man-db manpages locales bash-completion curl apt-utils \
+  unzip zip gzip bzip2 xz-utils openssh-client gpg ca-certificates
+locale-gen "$LANG" "en_US.UTF-8" "C.UTF-8"
 apt-get -y autoremove
 apt-get -y dist-upgrade
 apt-get -y dist-clean
 EOF
 
-# Set hostname and add the default non-root user
-ARG HOSTNAME
+# add the default non-root user with sudo permission
 ARG USERNAME
 ARG USER_UID
 ARG USER_GID
 ARG USER_GECOS
 RUN <<EOF
-echo $HOSTNAME > /etc/hostname
-hostname $HOSTNAME
 groupadd --gid $USER_GID $USERNAME
 useradd -s /bin/bash --uid $USER_UID --gid $USER_GID --comment "$USER_GECOS" -m $USERNAME
 echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME
@@ -68,4 +63,4 @@ USER ${USERNAME}
 LABEL description="Ubuntu Development Container Base" \
       author="rjstoneus@gmail.com" \
       maintainer="rjstoneus@gmail.com" \
-      version="0.4.0"
+      version="0.4.1"
